# configuration for "master" branch
# build in Release mode
-
  environment:
    packageVersion: 0.9.0

  version: '{branch}-v0.9.0-{build}'
  image: Visual Studio 2017

  install:
    - cmd: appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe

  cache:
    - packages -> **\packages.config

  pull_requests:
    do_not_increment_build_number: true

  skip_branch_with_pr: true

  before_build:
    - cmd: nuget restore

  after_test:
    - cmd: nuget pack Source\Lib\%APPVEYOR_PROJECT_NAME%\%APPVEYOR_PROJECT_NAME%.nuspec -OutputDirectory Build\Lib\%CONFIGURATION% -BasePath Source\Lib\%APPVEYOR_PROJECT_NAME% -Properties buildConfig=Release
    - ps: Get-ChildItem .\Build\Lib\Release\TraktApiSharp*.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }

  build:
    verbosity: minimal

  branches:
    only:
      - master

  configuration: Release

  artifacts:
    - path: Build\Lib\Release\TraktApiSharp.dll
      name: Assembly
    - path: Build\Lib\Release\TraktApiSharp.pdb
      name: AssemblyPDB
    - path: Build\Lib\Release\TraktApiSharp.xml
      name: DocumentationXML

  deploy:
    - provider: NuGet
      api_key:
        secure: SN3+YTcNTLpLVVD+/VA9UV2r6EWhR60wVcmZlKOhQwpS98bqSymIA+gDT+yYYnKA
      skip_symbols: true
      symbol_server:
      artifact: TraktApiSharp.$(packageVersion).nupkg
      on:
        appveyor_repo_tag: true

# configuration for all branches starting from "dev-"
# build in Debug mode
-
  version: '{branch}-{build}'
  image: Visual Studio 2017

  install:
    - cmd: appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe

  cache:
    - packages -> **\packages.config

  pull_requests:
    do_not_increment_build_number: true

  skip_branch_with_pr: true

  before_build:
    - cmd: nuget restore

  after_test:
    - cmd: nuget pack Source\Lib\%APPVEYOR_PROJECT_NAME%\%APPVEYOR_PROJECT_NAME%.nuspec -OutputDirectory Build\Lib\%CONFIGURATION% -BasePath Source\Lib\%APPVEYOR_PROJECT_NAME% -Properties buildConfig=Debug
    - ps: Get-ChildItem .\Build\Lib\Debug\TraktApiSharp*.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }

  build:
    verbosity: minimal

  branches:
    only:
      - dev
      - /dev-.*/

  configuration: Debug

  artifacts:
    - path: Build\Lib\Debug\TraktApiSharp.dll
      name: DebugAssembly
    - path: Build\Lib\Debug\TraktApiSharp.pdb
      name: DebugAssemblyPDB
    - path: Build\Lib\Debug\TraktApiSharp.xml
      name: DebugDocumentationXML

# "fall back" configuration for all other branches
# no "branches" section defined
# do not deploy at all
-
  version: '{branch}-{build}'
  image: Visual Studio 2017

  install:
    - cmd: appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe

  cache:
    - packages -> **\packages.config

  pull_requests:
    do_not_increment_build_number: true

  skip_branch_with_pr: true

  before_build:
    - cmd: nuget restore

  build:
    verbosity: minimal

  configuration: Debug

  artifacts:
    - path: Build\Lib\Debug\TraktApiSharp.dll
      name: DebugAssembly
    - path: Build\Lib\Debug\TraktApiSharp.pdb
      name: DebugAssemblyPDB
    - path: Build\Lib\Debug\TraktApiSharp.xml
      name: DebugDocumentationXML
